"""Data-driven correction rules — the extensible spelling-fix layer.

The hand-tuned regex table in :mod:`terminology` is the developer-maintained
core. *This* module is the part that scales: simple ``misheard -> correct``
rules live in editable YAML, not Python, so they can be reviewed in a diff,
generated by the usage miner (:mod:`scripts.mine_corrections`), and added by a
radiologist through the desktop/web UI — no code change, no redeploy.

Two files are merged, in this precedence (later wins on conflict):

1. ``resources/corrections.yaml`` — shipped rules (in the repo, reviewed).
2. ``user_corrections.yaml`` in the data dir — the site's own rules, added via
   the UI. Kept separate so an app update never clobbers them.

Rule schema (every field except ``pattern``/``replacement`` is optional)::

    - id: pleural-effusion
      pattern: "plural"                 # literal word, or raw regex if regex:true
      replacement: "pleural"
      context_after:  [effusion, space] # only fire when followed by one of these
      context_before: [the, a]          # only fire when preceded by one of these
      case_sensitive: false             # default false
      regex: false                      # if true, pattern is used verbatim
      note: "real-word homophone"

Context guards are what make real-word homophones safe: ``plural -> pleural``
only fires before an anatomical word, so grammatical "plural form" is untouched.
Authors never hand-write lookarounds — they list trigger words.

Offline / lossless: if PyYAML is missing or a file is malformed, that source
contributes no rules and the pipeline runs on whatever did load. A single bad
rule is skipped, not fatal.
"""

from __future__ import annotations

import logging
import re
import threading
from pathlib import Path
from typing import Callable, List, Optional, Pattern, Tuple

logger = logging.getLogger(__name__)

# (compiled_pattern, replacement_callable)
CompiledRule = Tuple[Pattern, Callable[[re.Match], str]]

_SHIPPED_PATH = Path(__file__).resolve().parent / "resources" / "corrections.yaml"

_CACHE: Optional[List[CompiledRule]] = None
_LOCK = threading.Lock()


# ---------------------------------------------------------------------------
# Compilation
# ---------------------------------------------------------------------------

def _alternation(words: List[str]) -> str:
    """``["a", "b"]`` -> ``(?:a|b)`` with each alternative escaped."""
    return "(?:" + "|".join(re.escape(str(w)) for w in words) + ")"


def compile_rule(rule: dict) -> Optional[CompiledRule]:
    """Compile one rule dict into ``(pattern, repl_func)`` or ``None`` if invalid.

    The replacement is a function (not a string) so that user-supplied text
    containing ``\\1`` or ``$`` is treated literally, never as a backreference.
    """
    pattern = rule.get("pattern")
    replacement = rule.get("replacement")
    if not pattern or replacement is None:
        logger.warning("Skipping correction rule missing pattern/replacement: %r", rule)
        return None

    is_regex = bool(rule.get("regex"))
    core = str(pattern) if is_regex else rf"\b{re.escape(str(pattern))}\b"

    before = rule.get("context_before") or []
    after = rule.get("context_after") or []

    # context_before is captured (variable-width lookbehind is unsupported) and
    # re-emitted; context_after is a zero-width lookahead.
    prefix = rf"(?P<_pre>\b{_alternation(before)}\s+)" if before else ""
    suffix = rf"(?=\s+{_alternation(after)}\b)" if after else ""
    expr = f"{prefix}{core}{suffix}"

    flags = 0 if rule.get("case_sensitive") else re.IGNORECASE
    try:
        compiled = re.compile(expr, flags)
    except re.error as exc:
        logger.warning("Skipping correction rule %r — bad regex: %s", rule.get("id"), exc)
        return None

    repl_text = str(replacement)

    def _repl(m: re.Match, _repl_text: str = repl_text, _has_pre: bool = bool(before)) -> str:
        pre = m["_pre"] if _has_pre else ""
        return f"{pre}{_repl_text}"

    return compiled, _repl


def _load_file(path: Path) -> List[CompiledRule]:
    """Parse and compile every rule in *path*; missing/bad file -> ``[]``."""
    if not path.exists():
        return []
    try:
        import yaml  # lazy: optional dep, keeps the core offline-safe
    except ImportError:
        logger.warning("PyYAML not installed; correction rules from %s skipped", path.name)
        return []
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    except Exception as exc:
        logger.warning("Could not parse correction rules %s: %s", path, exc)
        return []
    if not isinstance(raw, list):
        logger.warning("Correction rules in %s must be a list; ignoring", path)
        return []
    compiled = [c for r in raw if isinstance(r, dict) and (c := compile_rule(r))]
    logger.info("Loaded %d correction rules from %s", len(compiled), path.name)
    return compiled


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def _load_all() -> List[CompiledRule]:
    """User rules first, then shipped.

    Order matters: rules are applied as a sequence of substitutions, so a user
    rule with the same ``pattern`` as a shipped one must run first — otherwise
    the shipped rule would consume the word before the user's replacement could
    win. Running user rules first makes "user overrides win on conflict" true.
    """
    rules: List[CompiledRule] = []
    try:
        from src.features.file_manager import user_corrections_path
        rules += _load_file(user_corrections_path())
    except Exception as exc:  # never let user-file issues break the pipeline
        logger.debug("No user correction rules loaded: %s", exc)
    rules += _load_file(_SHIPPED_PATH)
    return rules


def get_rules() -> List[CompiledRule]:
    """Return the cached compiled rule list, loading on first use."""
    global _CACHE
    if _CACHE is not None:
        return _CACHE
    with _LOCK:
        if _CACHE is None:
            _CACHE = _load_all()
        return _CACHE


def invalidate_cache() -> None:
    """Drop the cache so the next call reloads (call after the UI edits rules)."""
    global _CACHE
    with _LOCK:
        _CACHE = None


def apply_data_rules(text: str) -> str:
    """Apply every data-driven correction rule, in load order, to *text*."""
    for pattern, repl in get_rules():
        text = pattern.sub(repl, text)
    return text


# ---------------------------------------------------------------------------
# User-rule editing (shared by the desktop dialog and the web endpoints)
# ---------------------------------------------------------------------------

def load_user_rules() -> List[dict]:
    """Return the raw user rule dicts from ``user_corrections.yaml`` (or ``[]``)."""
    from src.features.file_manager import user_corrections_path
    path = user_corrections_path()
    if not path.exists():
        return []
    try:
        import yaml
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    except Exception as exc:
        logger.warning("Could not read user correction rules: %s", exc)
        return []
    return [r for r in data if isinstance(r, dict)]


def save_user_rules(rules: List[dict]) -> None:
    """Persist *rules* to ``user_corrections.yaml`` and refresh the cache.

    Each rule must at least have ``pattern`` and ``replacement``; invalid rules
    are dropped so a bad entry can never poison the pipeline. Raises only if the
    file cannot be written.
    """
    import yaml
    from src.features.file_manager import user_corrections_path

    clean: List[dict] = []
    for r in rules:
        if not isinstance(r, dict) or not r.get("pattern") or r.get("replacement") is None:
            continue
        # Validate it actually compiles before we persist it.
        if compile_rule(r) is None:
            continue
        clean.append(r)

    path = user_corrections_path()
    header = (
        "# Site-added correction rules — editable via Settings -> Correction Rules\n"
        "# (desktop) or the web app. Schema matches the shipped corrections.yaml.\n"
        "# These override shipped rules and survive app updates.\n\n"
    )
    path.write_text(header + yaml.safe_dump(clean, sort_keys=False, allow_unicode=True),
                    encoding="utf-8")
    invalidate_cache()
