"""
MSK Radiology Quick-Phrase Macro Library.

Organised by body region.  Each entry is a (button_label, report_text) tuple.
Button labels are kept short so they fit the sidebar; report_text is the full
professional phrase inserted into the editor.
"""

from typing import Dict, List, Tuple

# Type alias for clarity
MacroEntry = Tuple[str, str]
MacroLibrary = Dict[str, List[MacroEntry]]

MACROS: MacroLibrary = {

    # -----------------------------------------------------------------------
    "General": [
        ("Normal study",
         "No acute abnormality identified."),
        ("No fracture",
         "No acute fracture or dislocation."),
        ("No soft tissue mass",
         "No significant soft tissue mass or abnormal enhancement."),
        ("Marrow signal normal",
         "Normal bone marrow signal throughout."),
        ("No avascular necrosis",
         "No imaging features of avascular necrosis."),
        ("No stress fracture",
         "No evidence of stress fracture or bone stress injury."),
        ("Post-op changes",
         "Post-operative changes in keeping with previous surgery. No evidence of complication."),
        ("Soft tissue oedema",
         "Mild soft tissue oedema noted in the region."),
        ("Incidental finding",
         "Incidental finding noted. Clinical correlation recommended."),
        ("Previous comparison",
         "Comparison with previous imaging shows no significant interval change."),
    ],

    # -----------------------------------------------------------------------
    "Knee": [
        ("MM normal",
         "Medial meniscus demonstrates normal morphology and signal."),
        ("LM normal",
         "Lateral meniscus demonstrates normal morphology and signal."),
        ("MM posterior horn tear",
         "Complex tear of the posterior horn of the medial meniscus."),
        ("LM posterior horn tear",
         "Complex tear of the posterior horn of the lateral meniscus."),
        ("Meniscal root tear",
         "Posterior root tear of the medial meniscus with radial extension."),
        ("ACL intact",
         "Anterior cruciate ligament intact with normal signal and course."),
        ("ACL complete tear",
         "Complete rupture of the anterior cruciate ligament. Ligament fibres are disrupted with surrounding oedema."),
        ("ACL partial tear",
         "Partial-thickness tear of the anterior cruciate ligament."),
        ("PCL intact",
         "Posterior cruciate ligament intact with normal signal."),
        ("MCL intact",
         "Medial collateral ligament intact."),
        ("LCL intact",
         "Lateral collateral ligament complex intact."),
        ("No effusion",
         "No significant joint effusion."),
        ("Moderate effusion",
         "Moderate joint effusion with mild synovial thickening."),
        ("Cartilage normal",
         "Articular cartilage of normal thickness and signal throughout all compartments."),
        ("Medial OA",
         "Medial compartment chondral thinning and subchondral signal change consistent with osteoarthritis."),
        ("Patellofemoral chondrosis",
         "Patellofemoral chondromalacia, Outerbridge grade II, with focal articular surface irregularity."),
        ("Subchondral BMO",
         "Subchondral bone marrow oedema in keeping with reactive/post-traumatic change."),
        ("Baker's cyst",
         "Baker's cyst in the posteromedial aspect of the knee measuring approximately ___ x ___ mm."),
        ("Hoffa's fat pad normal",
         "Hoffa's infrapatellar fat pad appears normal without impingement."),
        ("Patellar tendon normal",
         "Patellar tendon intact with normal morphology and signal throughout."),
        ("Patellar tendinopathy",
         "Patellar tendinopathy at the proximal insertion without full-thickness tear."),
        ("Quadriceps tendon normal",
         "Quadriceps tendon intact."),
        ("IT band normal",
         "Iliotibial band intact without thickening."),
        ("Tricompartmental OA",
         "Tricompartmental osteoarthritic change with joint space narrowing, subchondral sclerosis, and marginal osteophytosis."),
    ],

    # -----------------------------------------------------------------------
    "Shoulder": [
        ("Rotator cuff intact",
         "Rotator cuff tendons are intact with normal morphology and signal throughout."),
        ("Supraspinatus normal",
         "Supraspinatus tendon intact with normal morphology and signal."),
        ("Supraspinatus full tear",
         "Full-thickness tear of the supraspinatus tendon measuring approximately ___ mm in the anteroposterior dimension."),
        ("Supraspinatus partial (articular)",
         "Partial-thickness articular-surface tear of the supraspinatus tendon without full-thickness extension."),
        ("Supraspinatus partial (bursal)",
         "Partial-thickness bursal-surface tear of the supraspinatus tendon."),
        ("Infraspinatus normal",
         "Infraspinatus tendon intact with normal signal."),
        ("Infraspinatus tear",
         "Full-thickness tear of the infraspinatus tendon."),
        ("Subscapularis normal",
         "Subscapularis tendon intact."),
        ("Teres minor normal",
         "Teres minor intact."),
        ("Labrum normal",
         "Glenoid labrum intact without evidence of tear or detachment."),
        ("SLAP tear",
         "Superior labral tear from anterior to posterior (SLAP lesion)."),
        ("Bankart lesion",
         "Anterior labral tear consistent with a Bankart lesion. No associated bony Bankart defect."),
        ("HAGL lesion",
         "Humeral avulsion of the glenohumeral ligament (HAGL) noted."),
        ("AC joint normal",
         "Acromioclavicular joint normal."),
        ("AC joint OA",
         "Acromioclavicular joint osteoarthritic change with inferior osteophytes contributing to subacromial narrowing."),
        ("No subacromial impingement",
         "Adequate subacromial space. No significant subacromial impingement."),
        ("Subacromial bursitis",
         "Subacromial-subdeltoid bursitis with bursal fluid and wall thickening."),
        ("Biceps tendon normal",
         "Long head of biceps tendon in normal position with normal signal."),
        ("Biceps tendon tear",
         "Complete rupture of the long head of biceps tendon with proximal retraction."),
        ("Glenohumeral OA",
         "Glenohumeral joint osteoarthritic change with marginal osteophytosis and joint space narrowing."),
        ("Hill-Sachs lesion",
         "Hill-Sachs compression deformity of the posterior superior humeral head."),
        ("No GH effusion",
         "No significant glenohumeral joint effusion."),
        ("Os acromiale",
         "Os acromiale noted at the acromial tip."),
    ],

    # -----------------------------------------------------------------------
    "Hip": [
        ("Labrum normal",
         "Acetabular labrum intact without evidence of tear."),
        ("Labral tear anterosup",
         "Labral tear at the anterosuperior aspect of the acetabular labrum with para-labral cyst."),
        ("Cartilage normal",
         "Articular cartilage of normal thickness and signal bilaterally."),
        ("Femoral head normal",
         "Normal morphology and signal of the femoral head without evidence of avascular necrosis."),
        ("AVN early",
         "Early avascular necrosis of the femoral head: subchondral signal change without articular surface collapse (ARCO Stage I-II)."),
        ("AVN collapse",
         "Avascular necrosis of the femoral head with subchondral fracture and articular surface collapse (ARCO Stage III)."),
        ("No effusion",
         "No significant hip joint effusion."),
        ("Iliopsoas normal",
         "Iliopsoas tendon and muscle belly normal."),
        ("Iliopsoas tendinopathy",
         "Iliopsoas tendinopathy at the lesser trochanter insertion."),
        ("Gluteal tendons normal",
         "Gluteus medius and minimus tendons intact at the greater trochanter."),
        ("Gluteal tendinopathy",
         "Gluteal tendinopathy at the greater trochanteric footprint without full-thickness tear."),
        ("Gluteal tear",
         "Full-thickness tear of the gluteus medius tendon at the greater trochanter."),
        ("Cam morphology",
         "Cam-type femoroacetabular morphology with reduced femoral head-neck offset."),
        ("Pincer morphology",
         "Pincer-type femoroacetabular morphology with acetabular over-coverage."),
        ("Hip OA",
         "Concentric joint space narrowing with marginal osteophytosis in keeping with hip osteoarthritis."),
        ("Trochanteric bursitis",
         "Trochanteric bursitis with bursal fluid and wall thickening."),
        ("Hamstring origin normal",
         "Hamstring tendons intact at the ischial tuberosity."),
        ("Hamstring origin tear",
         "High-grade partial/complete tear of the hamstring tendons at the ischial tuberosity origin."),
    ],

    # -----------------------------------------------------------------------
    "Lumbar Spine": [
        ("Normal alignment",
         "Vertebral alignment maintained. No spondylolisthesis."),
        ("Disc height normal",
         "Disc height and signal maintained at all levels."),
        ("Multilevel disc degeneration",
         "Multilevel degenerative disc disease with loss of disc height and T2 signal (desiccation)."),
        ("Disc bulge",
         "Broad-based disc bulge without significant central canal or foraminal compromise."),
        ("Disc protrusion",
         "Posterior disc protrusion causing moderate central canal stenosis."),
        ("Disc extrusion",
         "Disc extrusion with significant canal compromise and contact with the traversing nerve root."),
        ("No canal stenosis",
         "Spinal canal of normal calibre throughout. No significant central canal stenosis."),
        ("Moderate canal stenosis",
         "Moderate central canal stenosis."),
        ("Severe canal stenosis",
         "Severe central canal stenosis with compression of the cauda equina."),
        ("Foraminal stenosis",
         "Moderate bilateral neural foraminal narrowing secondary to disc-osteophyte complex and facet hypertrophy."),
        ("No cord signal change",
         "No intrinsic spinal cord signal change."),
        ("Conus normal",
         "Conus medullaris terminates at the level of L1/L2, within normal limits, with normal signal."),
        ("Cauda equina normal",
         "Cauda equina nerve roots appear unremarkable."),
        ("Facet OA",
         "Facet joint osteoarthritic change with joint space narrowing, subchondral sclerosis, and ligamentum flavum hypertrophy."),
        ("Schmorl's nodes",
         "Schmorl's node formation at multiple levels, in keeping with chronic degenerative change."),
        ("Modic type 1",
         "Modic type 1 end-plate signal change indicating active inflammatory end-plate degeneration."),
        ("Modic type 2",
         "Modic type 2 end-plate signal change indicating fatty end-plate degeneration."),
        ("Spondylolisthesis grade 1",
         "Grade I isthmic/degenerative spondylolisthesis."),
        ("Pars defect",
         "Pars interarticularis defect (spondylolysis) noted bilaterally."),
        ("No acute fracture",
         "No acute vertebral fracture or abnormal bone marrow signal change."),
        ("Epidural lipomatosis",
         "Mild epidural lipomatosis without significant canal compromise."),
    ],

    # -----------------------------------------------------------------------
    "Cervical Spine": [
        ("Normal alignment",
         "Cervical vertebral alignment maintained. Normal lordosis."),
        ("Disc degeneration",
         "Multilevel cervical spondylosis with disc desiccation and osteophyte formation."),
        ("Cord signal normal",
         "Spinal cord of normal morphology and signal throughout."),
        ("Cord compression",
         "Cord compression at ___ level with associated intrinsic T2 cord signal change."),
        ("No acute fracture",
         "No acute cervical fracture or ligamentous injury."),
        ("Foraminal stenosis",
         "Moderate neural foraminal narrowing at ___ level secondary to uncovertebral joint hypertrophy and disc-osteophyte complex."),
        ("Disc protrusion",
         "Posterolateral disc protrusion at ___ with foraminal compromise and contact with the exiting nerve root."),
        ("Posterior longitudinal ligament",
         "Ossification of the posterior longitudinal ligament contributing to canal stenosis."),
    ],

    # -----------------------------------------------------------------------
    "Thoracic Spine": [
        ("Normal alignment",
         "Thoracic vertebral alignment maintained. Normal kyphosis."),
        ("Disc degeneration",
         "Multilevel thoracic disc degenerative change."),
        ("No cord signal change",
         "Spinal cord of normal morphology and signal throughout the thoracic region."),
        ("Scheuermann's disease",
         "Scheuermann's disease with Schmorl's node formation and anterior vertebral wedging at multiple levels."),
        ("No acute fracture",
         "No acute thoracic vertebral fracture."),
        ("Compression fracture",
         "Compression fracture at ___ vertebral body with ___ % height loss. No retropulsion. Normal signal (chronic)."),
        ("Osteoporotic fracture",
         "Acute osteoporotic compression fracture at ___ with bone marrow oedema."),
    ],

    # -----------------------------------------------------------------------
    "Ankle / Foot": [
        ("Achilles normal",
         "Achilles tendon intact with normal morphology and signal throughout."),
        ("Achilles tendinopathy",
         "Mid-substance Achilles tendinopathy with tendon thickening and intrasubstance signal change, without full-thickness tear."),
        ("Achilles full tear",
         "Full-thickness tear of the Achilles tendon at the ___ level with ___ cm of retraction."),
        ("Peroneal tendons normal",
         "Peroneal tendons (peroneus longus and brevis) intact in their normal retro-malleolar positions."),
        ("Peroneus brevis split",
         "Longitudinal split tear of the peroneus brevis tendon at the retromalleolar groove."),
        ("Post tibial tendon normal",
         "Posterior tibial tendon intact with normal signal and calibre."),
        ("PTT tendinopathy",
         "Posterior tibial tendon tendinopathy (Johnson stage I) without tear."),
        ("ATFL intact",
         "Anterior talofibular ligament intact."),
        ("ATFL tear",
         "Tear of the anterior talofibular ligament with surrounding soft tissue oedema."),
        ("CFL intact",
         "Calcaneofibular ligament intact."),
        ("No OCD talar dome",
         "No osteochondral lesion of the talar dome."),
        ("OCD talar dome",
         "Osteochondral lesion of the medial/lateral talar dome measuring ___ x ___ mm."),
        ("Plantar fascia normal",
         "Plantar fascia of normal thickness and signal."),
        ("Plantar fasciitis",
         "Plantar fasciitis with thickening and increased T2 signal at the calcaneal insertion, without full-thickness tear."),
        ("No effusion",
         "No significant ankle joint effusion."),
        ("Morton's neuroma",
         "Interdigital neuroma in the third web space, consistent with Morton's neuroma, measuring approximately ___ mm."),
        ("Stress fracture",
         "Stress fracture of the ___ with surrounding periosteal oedema and bone marrow oedema."),
        ("Sinus tarsi syndrome",
         "Sinus tarsi syndrome with T2 signal change and loss of normal fat signal within the sinus tarsi."),
    ],

    # -----------------------------------------------------------------------
    "Wrist / Hand": [
        ("TFCC normal",
         "Triangular fibrocartilage complex (TFCC) intact."),
        ("TFCC central perforation",
         "Central perforation of the triangular fibrocartilage complex (TFCC Palmer class 1A)."),
        ("Scaphoid normal",
         "No fracture of the scaphoid. Normal bone marrow signal throughout."),
        ("Scaphoid waist fracture",
         "Undisplaced fracture of the scaphoid waist with surrounding bone marrow oedema. No avascular necrosis of the proximal pole."),
        ("Scaphoid AVN",
         "Avascular necrosis of the proximal scaphoid pole with T1 hypointensity."),
        ("Carpal alignment normal",
         "Normal carpal alignment without intercarpal instability."),
        ("SLIL intact",
         "Scapholunate interosseous ligament intact."),
        ("SLIL tear",
         "Complete tear of the scapholunate interosseous ligament with scapholunate interval widening."),
        ("LTIL intact",
         "Lunotriquetral interosseous ligament intact."),
        ("Flexor tendons normal",
         "Flexor tendons intact within the carpal tunnel without tenosynovitis."),
        ("Carpal tunnel normal",
         "Median nerve of normal calibre and signal within the carpal tunnel."),
        ("Carpal tunnel syndrome",
         "Median nerve enlargement and T2 signal change at the level of the carpal tunnel inlet, in keeping with carpal tunnel syndrome."),
        ("De Quervain's",
         "Tenosynovitis of the first extensor compartment (APL and EPB tendons), consistent with de Quervain's disease."),
        ("Ganglion cyst",
         "Ganglion cyst arising from the ___ aspect of the wrist measuring ___ x ___ mm."),
        ("Distal radioulnar normal",
         "Distal radioulnar joint congruent with no evidence of instability."),
    ],

    # -----------------------------------------------------------------------
    "Elbow": [
        ("CET origin normal",
         "Common extensor tendon origin intact with normal morphology."),
        ("Lateral epicondylitis",
         "Partial-thickness tearing and tendinopathy of the common extensor tendon origin, consistent with lateral epicondylitis."),
        ("CFT origin normal",
         "Common flexor tendon origin intact."),
        ("Medial epicondylitis",
         "Tendinopathy of the common flexor tendon origin, consistent with medial epicondylitis."),
        ("UCL intact",
         "Ulnar collateral ligament (UCL) intact."),
        ("UCL tear",
         "Complete tear of the ulnar collateral ligament with medial instability."),
        ("RCL intact",
         "Radial collateral ligament complex intact."),
        ("No OCD capitellum",
         "No osteochondral defect of the capitellum."),
        ("OCD capitellum",
         "Osteochondral defect of the capitellum with partial articular surface disruption."),
        ("No effusion",
         "No significant elbow joint effusion."),
        ("Moderate effusion",
         "Moderate elbow joint effusion."),
        ("Distal biceps normal",
         "Distal biceps tendon intact at the radial tuberosity with normal signal."),
        ("Distal biceps tear",
         "Complete rupture of the distal biceps tendon with ___ cm of proximal retraction."),
        ("Triceps normal",
         "Triceps tendon intact at the olecranon."),
        ("Cubital tunnel",
         "Ulnar nerve at the cubital tunnel of normal calibre and signal."),
        ("Ulnar nerve subluxation",
         "Ulnar nerve subluxation over the medial epicondyle noted."),
    ],

    # -----------------------------------------------------------------------
    "Pelvis / SI Joints": [
        ("SI joints normal",
         "Sacroiliac joints demonstrate normal morphology and signal bilaterally. No sacroiliitis."),
        ("Active sacroiliitis",
         "Active sacroiliitis with subchondral bone marrow oedema (SPARCC score ___) bilaterally, consistent with axial spondyloarthropathy."),
        ("Structural sacroiliitis",
         "Structural sacroiliac changes including erosions and partial ankylosis, in keeping with established spondyloarthropathy."),
        ("Pelvis marrow normal",
         "Normal bone marrow signal throughout the pelvis and proximal femora."),
        ("No pelvic fracture",
         "No acute pelvic fracture."),
        ("Pubic symphysis normal",
         "Pubic symphysis normal."),
        ("Osteitis pubis",
         "Osteitis pubis with subchondral signal change and erosive change at the pubic symphysis."),
        ("Hamstring origin normal",
         "Conjoint hamstring tendons intact at the ischial tuberosity."),
        ("Hamstring origin avulsion",
         "Avulsion injury of the hamstring tendons at the ischial tuberosity."),
        ("No soft tissue lesion",
         "No pelvic soft tissue lesion identified."),
        ("ASIS avulsion",
         "Anterior superior iliac spine avulsion injury with surrounding oedema."),
        ("AIIS avulsion",
         "Anterior inferior iliac spine avulsion injury."),
    ],

}

# ---------------------------------------------------------------------------
# Helper – return all region names in display order
# ---------------------------------------------------------------------------

REGION_ORDER: List[str] = list(MACROS.keys())
